# Setup
title: Amber
description: Note Something Here
url: https://amberli.github.io
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
    remote_theme: vszhub/not-pure-poole

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
Self:
  username: amberli-80486
  # card: summary
logo: logo.png
social:
  name: Amber Li
  links:
    - https://github.com/amberli-80486
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Enable Google Analytics tracking
google_analytics: G-72NSXNZ651

# Specify the author for blog posts
author:
  name: Amber
  url: https://github.com/amberli-80486
  email: amberli1729@gmail.com
